"""
Curated list of core data science / ML concepts for the daily briefing.

Each run the synthesis LLM picks ONE concept from this list that is most
relevant to today's research papers. Using a fixed list prevents hallucinated
or trivially obvious concept choices and ensures coverage across the field.
"""

CORE_DS_CONCEPTS: list[str] = [
    # Foundations & Math
    "Gradient Descent",
    "Stochastic Gradient Descent (SGD)",
    "Mini-Batch Gradient Descent",
    "Backpropagation",
    "Chain Rule and Automatic Differentiation",
    "Bias-Variance Tradeoff",
    "Overfitting and Regularization",
    "L1 and L2 Regularization",
    "Cross-Validation",
    "Maximum Likelihood Estimation",
    "Maximum A Posteriori (MAP) Estimation",
    "Bayesian Inference",
    "Bayes' Theorem",
    "Information Theory and Entropy",
    "KL Divergence",
    "Jensen-Shannon Divergence",
    "Mutual Information",
    "Cross-Entropy Loss",
    "Log-Likelihood",
    "Probability Distributions (Gaussian, Bernoulli, Categorical)",
    "Monte Carlo Estimation",
    "Importance Sampling",
    "Markov Chains",
    "Convexity and Non-Convex Optimization",
    "Lagrange Multipliers and Constrained Optimization",
    "Linear Algebra for ML (Eigenvalues, SVD, Matrix Factorization)",

    # Classical ML
    "Linear Regression",
    "Logistic Regression",
    "Decision Trees",
    "Random Forests",
    "Gradient Boosting (XGBoost / LightGBM)",
    "AdaBoost and Ensemble Methods",
    "Support Vector Machines",
    "Kernel Methods and the Kernel Trick",
    "K-Nearest Neighbors",
    "Naive Bayes",
    "K-Means Clustering",
    "DBSCAN and Density-Based Clustering",
    "Hierarchical Clustering",
    "Gaussian Mixture Models",
    "Principal Component Analysis (PCA)",
    "Independent Component Analysis (ICA)",
    "t-SNE and UMAP for Dimensionality Reduction",
    "Expectation-Maximization (EM)",
    "Hidden Markov Models",
    "Conditional Random Fields (CRFs)",

    # Neural Networks
    "Activation Functions (ReLU, GELU, SiLU)",
    "Sigmoid and Softmax Functions",
    "Batch Normalization",
    "Layer Normalization",
    "Group Normalization",
    "RMS Normalization (RMSNorm)",
    "Dropout",
    "Weight Decay",
    "Residual Connections (ResNets)",
    "Dense Connections (DenseNets)",
    "Convolutional Neural Networks (CNNs)",
    "Depthwise Separable Convolutions",
    "Dilated / Atrous Convolutions",
    "Recurrent Neural Networks (RNNs)",
    "Long Short-Term Memory (LSTM)",
    "Gated Recurrent Units (GRUs)",
    "Attention Mechanism",
    "Self-Attention",
    "Multi-Head Attention",
    "Cross-Attention",
    "Transformer Architecture",
    "Encoder-Decoder Architecture",
    "Positional Encoding",
    "Rotary Positional Embeddings (RoPE)",
    "ALiBi (Attention with Linear Biases)",
    "Feed-Forward Networks in Transformers",

    # Training & Optimization
    "Adam Optimizer",
    "AdamW Optimizer",
    "RMSProp",
    "Momentum",
    "Nesterov Accelerated Gradient",
    "Learning Rate Scheduling",
    "Cosine Annealing",
    "Warmup and Cooldown Schedules",
    "Weight Initialization (Xavier, Kaiming)",
    "Gradient Clipping",
    "Mixed Precision Training (FP16 / BF16)",
    "Gradient Checkpointing",
    "Gradient Accumulation",
    "Data Parallelism",
    "Model Parallelism",
    "Pipeline Parallelism",
    "Tensor Parallelism",
    "ZeRO Optimizer (DeepSpeed)",
    "Knowledge Distillation",
    "Self-Distillation",
    "Transfer Learning",
    "Fine-Tuning",
    "Parameter-Efficient Fine-Tuning (LoRA / QLoRA)",
    "Adapter Layers",
    "Prefix Tuning",
    "Prompt Tuning",
    "Catastrophic Forgetting and Continual Learning",

    # Language Models
    "Tokenization and Byte-Pair Encoding (BPE)",
    "WordPiece and SentencePiece Tokenization",
    "Masked Language Modeling (MLM)",
    "Causal Language Modeling (CLM)",
    "Next Token Prediction",
    "Perplexity",
    "In-Context Learning",
    "Few-Shot and Zero-Shot Learning",
    "Chain-of-Thought Prompting",
    "Tree-of-Thought Reasoning",
    "Self-Consistency Decoding",
    "Instruction Tuning",
    "Supervised Fine-Tuning (SFT)",
    "RLHF (Reinforcement Learning from Human Feedback)",
    "Direct Preference Optimization (DPO)",
    "Proximal Policy Optimization (PPO) for LLMs",
    "Constitutional AI and RLAIF",
    "Retrieval-Augmented Generation (RAG)",
    "Dense Retrieval and Bi-Encoders",
    "Reranking and Cross-Encoders",
    "Hallucination in LLMs",
    "Grounding and Factuality",
    "Tool Use in LLM Agents",
    "Function Calling",
    "Structured Output Generation",
    "Beam Search",
    "Top-k and Top-p (Nucleus) Sampling",
    "Temperature Scaling in Decoding",
    "Repetition Penalty",

    # Scaling & Efficiency
    "Scaling Laws",
    "Chinchilla Scaling Laws",
    "Compute-Optimal Training",
    "Mixture of Experts (MoE)",
    "Sparse MoE and Expert Routing",
    "Speculative Decoding",
    "Quantization (INT8, INT4, GGUF)",
    "Post-Training Quantization (PTQ)",
    "Quantization-Aware Training (QAT)",
    "Pruning (Unstructured and Structured)",
    "Weight Sharing",
    "Neural Architecture Search (NAS)",
    "FlashAttention",
    "FlashAttention-2 and Sliding Window Attention",
    "Key-Value (KV) Cache",
    "Paged Attention",
    "Continuous Batching",
    "Tensor Decomposition",
    "Context Window Extrapolation",
    "Long-Context Attention (RoPE, ALiBi, Yarn)",
    "Grouped-Query Attention (GQA)",
    "Multi-Query Attention (MQA)",

    # Generative Models
    "Variational Autoencoders (VAEs)",
    "Reparameterization Trick",
    "Generative Adversarial Networks (GANs)",
    "Mode Collapse in GANs",
    "Wasserstein GAN (WGAN)",
    "Normalizing Flows",
    "Diffusion Models (DDPM)",
    "DDIM and Accelerated Diffusion Sampling",
    "Score-Based Generative Models",
    "Flow Matching",
    "Rectified Flow",
    "Classifier-Free Guidance (CFG)",
    "Classifier Guidance",
    "Latent Diffusion Models",
    "Image Generation with Stable Diffusion",
    "ControlNet and Conditioned Generation",
    "Consistency Models",
    "Energy-Based Models",

    # Multimodal
    "CLIP and Contrastive Learning",
    "ALIGN and Noise-Contrastive Estimation",
    "Vision-Language Models (VLMs)",
    "Image Tokenization and VQ-VAE",
    "Cross-Modal Attention",
    "Visual Instruction Tuning",
    "Image-Text Alignment",
    "Video Understanding Models",
    "Audio-Visual Learning",
    "Speech Recognition (ASR) and Whisper",
    "Text-to-Image Generation",
    "Text-to-Video Generation",
    "Multimodal Chain-of-Thought",

    # Agents & Reinforcement Learning
    "Markov Decision Processes (MDPs)",
    "Bellman Equation",
    "Q-Learning and Deep Q-Networks (DQN)",
    "Policy Gradient Methods",
    "REINFORCE Algorithm",
    "Actor-Critic Methods",
    "Proximal Policy Optimization (PPO)",
    "Group Relative Policy Optimization (GRPO)",
    "Monte Carlo Tree Search (MCTS)",
    "Reward Modeling",
    "Reward Hacking and Specification Gaming",
    "Exploration vs. Exploitation",
    "Multi-Armed Bandits",
    "Model-Based RL",
    "World Models",
    "Multi-Agent Systems",
    "Hierarchical Reinforcement Learning",
    "Offline RL and Imitation Learning",
    "LLM Agents and Planning",
    "ReAct (Reasoning + Acting) Framework",
    "Reflection and Self-Critique in Agents",

    # Evaluation & Alignment
    "BLEU / ROUGE Scores",
    "MMLU and Benchmark Design",
    "Calibration and Uncertainty Estimation",
    "Conformal Prediction",
    "Human Evaluation of LLMs",
    "LLM-as-Judge",
    "Red-Teaming and Adversarial Evaluation",
    "AI Safety and Alignment",
    "Truthfulness and Honesty in LLMs",
    "Robustness and Distribution Shift",
    "Out-of-Distribution (OOD) Detection",
    "Adversarial Examples and Attacks",
    "Fairness and Bias in ML",
    "Interpretability and Explainability (SHAP, LIME)",
    "Mechanistic Interpretability",
    "Probing Classifiers",
    "Activation Patching and Causal Tracing",

    # Data
    "Synthetic Data Generation",
    "Data Augmentation",
    "Data Mixing and Curriculum Learning",
    "Class Imbalance Handling (SMOTE, Reweighting)",
    "Feature Engineering",
    "Embedding Spaces and Vector Similarity",
    "Cosine Similarity and Dot-Product Search",
    "Approximate Nearest Neighbor Search (FAISS, HNSW)",
    "Dataset Distillation",
    "Active Learning",
    "Semi-Supervised Learning",
    "Self-Supervised Learning",
    "Contrastive Self-Supervised Learning (SimCLR, MoCo)",
    "Masked Autoencoders (MAE)",

    # Graph & Structured
    "Graph Neural Networks (GNNs)",
    "Message Passing Neural Networks",
    "Graph Attention Networks (GATs)",
    "Node and Graph Classification",
    "Link Prediction",
    "Geometric Deep Learning",

    # Systems & MLOps
    "Experiment Tracking and Reproducibility",
    "Model Serving and Inference Optimization",
    "A/B Testing and Online Evaluation",
    "Feature Stores",
    "ML Pipelines and Orchestration",
    "Model Versioning and Registry",
    "Monitoring and Data Drift Detection",

    # Test-Time Compute
    "Test-Time Compute Scaling",
    "Best-of-N Sampling",
    "Process Reward Models (PRMs)",
    "Outcome Reward Models (ORMs)",
    "Majority Voting and Self-Consistency",
    "Iterative Refinement at Inference",
]
